import {
  Home,
  Box,
  DollarSign,
  Tag,
  Clipboard,
  Camera,
  AlignLeft,
  UserPlus,
  Users,
  Chrome,
  BarChart,
  Settings,
  Archive,
  LogIn,
} from 'react-feather'
console.log(
  "localStorage.getItem('businesscard')",
  localStorage.getItem('businesscard'),
)
export const MENUITEMS =
  localStorage.getItem('businesscard') == 'superadmin'
    ? [
        {
          path: '/orderlisttotal',
          title: '예약현황(전체)',
          icon: Home,
          type: 'link',
          badgeType: 'primary',
          active: false,
        },
        {
          path: '/orderlist',
          title: '예약현황',
          icon: Home,
          type: 'link',
          badgeType: 'primary',
          active: false,
        },
        {
          path: '/memberlist',
          title: '사업자회원현황',
          icon: Home,
          type: 'link',
          badgeType: 'primary',
          active: false,
        },
        {
          path: '/userlist',
          title: '유저현황',
          icon: Home,
          type: 'link',
          badgeType: 'primary',
          active: false,
        },
        {
          path: '/userlisttotal',
          title: '유저현황(전체)',
          icon: Home,
          type: 'link',
          badgeType: 'primary',
          active: false,
        },
        {
          path: '/creategroup',
          title: '그룹아이템 생성',
          icon: Home,
          type: 'link',
          badgeType: 'primary',
          active: false,
        },
        {
          path: '/paidorderlist',
          title: '데이터 보기',
          icon: Home,
          type: 'link',
          badgeType: 'primary',
          active: false,
        },
        {
          path: '/pages/create-excel',
          title: '엑셀업로드',
          icon: Home,
          type: 'link',
          badgeType: 'primary',
          active: false,
        },
        {
          path: '/pages/create-page',
          title: '예약 생성',
          icon: Home,
          type: 'link',
          badgeType: 'primary',
          active: false,
        },
        {
          path: '/pages/manage-page',
          title: '예약 관리',
          icon: Home,
          type: 'link',
          badgeType: 'primary',
          active: false,
        },
        {
          path: '/settings/profile',
          title: '프로필 관리',
          icon: Home,
          type: 'link',
          badgeType: 'primary',
          active: false,
        },
        {
          path: '/pages/logout',
          title: '로그아웃',
          icon: Home,
          type: 'link',
          badgeType: 'primary',
          active: false,
        },
      ]
    : [
        {
          path: '/orderlist',
          title: '예약현황',
          icon: Home,
          type: 'link',
          badgeType: 'primary',
          active: false,
        },
        {
          path: '/userlist',
          title: '유저현황',
          icon: Home,
          type: 'link',
          badgeType: 'primary',
          active: false,
        },
        {
          path: '/creategroup',
          title: '그룹아이템 생성',
          icon: Home,
          type: 'link',
          badgeType: 'primary',
          active: false,
        },
        {
          path: '/paidorderlist',
          title: '데이터 보기',
          icon: Home,
          type: 'link',
          badgeType: 'primary',
          active: false,
        },

        {
          path: '/pages/create-page',
          title: '예약 생성',
          icon: Home,
          type: 'link',
          badgeType: 'primary',
          active: false,
        },
        {
          path: '/pages/manage-page',
          title: '예약 관리',
          icon: Home,
          type: 'link',
          badgeType: 'primary',
          active: false,
        },
        {
          path: '/settings/profile',
          title: '프로필 관리',
          icon: Home,
          type: 'link',
          badgeType: 'primary',
          active: false,
        },
        {
          path: '/pages/logout',
          title: '로그아웃',
          icon: Home,
          type: 'link',
          badgeType: 'primary',
          active: false,
        },
      ]
